// Complete Life Info contact directory - all 9 categories with full data
export const LIFE_INFO_CATEGORIES = [
  {
    id: "emergency",
    icon: "🚨",
    korean: "긴급 도움",
    english: "Emergency",
    items: [
      { name: "긴급신고 (119)", description: "화재, 응급의료, 구조", phone: "119" },
      { name: "경찰신고 (112)", description: "범죄, 사고 신고", phone: "112" },
      { name: "외국인 긴급상담 핫라인", description: "24시간 긴급상담", phone: "1577-0365" },
      { name: "다문화 가족 지원 핫라인", description: "생활, 법률, 건강 상담", phone: "1577-1366" },
      { name: "근로자 상담 핫라인", description: "노동문제 상담", phone: "1350" },
      { name: "여성 폭력 상담 핫라인", description: "가정폭력, 성폭력 상담", phone: "1366" },
      { name: "정신건강 위기상담", description: "정신건강, 자살예방", phone: "1393" },
    ],
  },
  {
    id: "visa",
    icon: "📋",
    korean: "비자/체류/출입국",
    english: "Visa/Stay/Immigration",
    items: [
      { name: "대한민국 출입국·외국인청", description: "출입국 종합 안내", phone: "1345", url: "https://www.hikorea.go.kr" },
      { name: "비자 포털", description: "비자 신청 및 안내", phone: "1345", url: "https://www.visa.go.kr" },
      { name: "하이코리아 (Hi Korea)", description: "외국인을 위한 종합 정보", phone: "02-1345", url: "https://www.hikorea.go.kr" },
      { name: "서울 출입국·외국인청", description: "서울 지역 비자 업무", phone: "02-2650-6000" },
    ],
  },
  {
    id: "admin",
    icon: "🏛️",
    korean: "행정·공공서비스",
    english: "Admin/Public Services",
    items: [
      { name: "하이코리아", description: "외국인 종합 안내 포털", phone: "02-1345", url: "https://www.hikorea.go.kr" },
      { name: "다문화교육포털", description: "다문화 교육 정보", url: "https://www.nile.or.kr", email: "edu4mc@nile.or.kr" },
      { name: "부산민원 120", description: "부산 외국인 민원", phone: "051-120", url: "https://www.busan.go.kr/foreign" },
      { name: "김포시청 생활민원안내", description: "김포시 외국인 생활 안내", phone: "031-980-2114" },
      { name: "수원시 외국인주민 생활안내", description: "수원시 외국인 지원", phone: "031-5191-2990" },
    ],
  },
  {
    id: "medical",
    icon: "🏥",
    korean: "의료·건강",
    english: "Medical/Health",
    items: [
      { name: "서울외국인포털 의료통역지원", description: "다국어 의료 통역", phone: "070-4523-1394", url: "https://care.webring.kr" },
      { name: "서울아산병원 국제진료센터", description: "외국인 진료 가능", phone: "02-3010-5001" },
      { name: "희망진료센터 서울", description: "취약계층 무료 진료", phone: "02-2002-8684" },
      { name: "희망진료센터 인천", description: "취약계층 무료 진료", phone: "032-899-4469" },
      { name: "희망진료센터 통영", description: "취약계층 무료 진료", phone: "055-640-1779" },
      { name: "희망진료센터 거창", description: "취약계층 무료 진료", phone: "055-949-3368" },
      { name: "희망진료센터 영주", description: "취약계층 무료 진료", phone: "054-630-0167" },
      { name: "희망진료센터 경인권", description: "취약계층 무료 진료", phone: "032-899-4351" },
      { name: "평택시 외국인 무료진료", description: "평택 외국인 무료 진료", phone: "031-8024-5559" },
      { name: "서울대학교병원 국제진료", description: "외국인 진료 가능", phone: "02-2072-0500", url: "https://www.snuh.org", email: "international@snuh.org" },
    ],
  },
  {
    id: "labor",
    icon: "💼",
    korean: "노동·취업",
    english: "Labor/Employment",
    items: [
      { name: "고용허가제 EPS (고용24)", description: "외국인 고용 허가", phone: "1577-7114", url: "https://www.eps.go.kr" },
      { name: "한국산업인력공단", description: "직업 능력 개발 지원", phone: "1577-0071", url: "https://www.kila.or.kr" },
      { name: "외국국적동포 취업교육", description: "재외동포 취업 지원", phone: "1577-0071" },
      { name: "노동인권회관", description: "노동 인권 상담", phone: "02-749-6052" },
      { name: "Return Job", description: "귀국 후 일자리 지원", phone: "052-714-8543" },
      { name: "이주노동자 노조", description: "이주노동자 권익 보호", phone: "02-2285-6068", url: "https://www.mtu.or.kr" },
    ],
  },
  {
    id: "legal",
    icon: "⚖️",
    korean: "법률·권리구제",
    english: "Legal/Rights",
    items: [
      { name: "이주민 지원 공익센터 감사와 동행", description: "이주민 법률 지원", phone: "02-537-5459" },
      { name: "공익법센터 어필", description: "난민 및 이주민 법률", phone: "02-3478-0529" },
      { name: "이주민센터 친구", description: "이주민 종합 지원", phone: "02-6406-7179" },
      { name: "공익인권법재단 공감", description: "인권 법률 지원", phone: "02-3675-7740" },
      { name: "난민인권센터", description: "난민 권리 보호", phone: "02-712-0620" },
      { name: "공익법단체 두루", description: "공익 법률 지원", phone: "02-6200-1853" },
    ],
  },
  {
    id: "support",
    icon: "🤝",
    korean: "상담센터·지원기관",
    english: "Support Centers",
    items: [
      { name: "서울외국인주민센터", description: "서울 외국인 종합 지원", phone: "02-2229-4900", url: "https://global.seoul.go.kr" },
      { name: "동부외국인주민센터", description: "서울 동부 외국인 지원", phone: "02-478-0126", url: "https://www.dfrc.or.kr" },
      { name: "강동외국인주민센터", description: "강동 외국인 지원", phone: "02-478-0126", url: "https://www.gdcenter.co.kr" },
      { name: "금천외국인주민센터", description: "금천 외국인 지원", phone: "02-2627-1242", url: "https://www.gmwc.or.kr" },
      { name: "성북외국인주민센터", description: "성북 외국인 지원", phone: "02-941-3274", url: "https://www.sbmwc.or.kr" },
      { name: "양천외국인주민센터", description: "양천 외국인 지원", phone: "02-2644-0570", url: "https://www.shinmok.or.kr" },
      { name: "은평외국인주민센터", description: "은평 외국인 지원", phone: "02-383-0196", url: "https://www.nokbeon.or.kr" },
      { name: "강남글로벌빌리지센터", description: "강남 글로벌 지원", phone: "02-3423-7960" },
      { name: "금천글로벌빌리지센터", description: "금천 글로벌 지원", phone: "02-2627-2884" },
      { name: "서래글로벌빌리지센터", description: "서래 글로벌 지원", phone: "02-2155-8949" },
      { name: "성북글로벌빌리지센터", description: "성북 글로벌 지원", phone: "02-2241-6381" },
      { name: "연남글로벌빌리지센터", description: "연남 글로벌 지원", phone: "02-6406-8151" },
      { name: "이촌글로벌빌리지센터", description: "이촌 글로벌 지원", phone: "02-2199-8881" },
      { name: "이태원글로벌빌리지센터", description: "이태원 글로벌 지원", phone: "02-2199-8883" },
    ],
  },
  {
    id: "korean-edu",
    icon: "📚",
    korean: "한국어·교육",
    english: "Korean/Education",
    items: [
      { name: "서울글로벌센터 한국어교육", description: "무료 한국어 교실", phone: "02-2075-4149", url: "https://global.seoul.go.kr" },
      { name: "한국이주노동자 복지회", description: "이주노동자 복지", phone: "02-858-4115", url: "https://www.miwel.kr" },
      { name: "서울외국인노동자센터", description: "외국인 노동자 지원", phone: "02-3672-9472" },
      { name: "사회통합프로그램 KIIP", description: "한국 사회 통합 교육", phone: "1345", url: "https://www.socinet.go.kr" },
      { name: "세종학당", description: "전 세계 한국어 교육", phone: "02-3708-9500", url: "https://www.iksi.or.kr" },
      { name: "서울시글로벌청소년교육센터", description: "청소년 글로벌 교육", phone: "02-2678-7191" },
      { name: "한국어능력시험 TOPIK", description: "TOPIK 시험 안내", phone: "02-3668-1331", url: "https://www.topik.go.kr" },
      { name: "누리 세종학당 (온라인)", description: "온라인 한국어 학습", phone: "02-6674-1743", url: "https://nuri.iksi.or.kr" },
      { name: "고려사이버대학교", description: "사이버 한국어 학습", phone: "02-6361-2000", url: "https://korean.cuk.edu" },
      { name: "EBS 두리안", description: "EBS 한국어 방송", phone: "1588-1580", url: "https://www.ebs.co.kr/durian" },
    ],
  },
  {
    id: "family",
    icon: "👨‍👩‍👧‍👦",
    korean: "가족·아동·여성",
    english: "Family/Children/Women",
    items: [
      { name: "서울시가족센터 1센터", description: "서울시 가족 지원", phone: "02-318-0227", url: "https://www.familyseoul.or.kr" },
      { name: "서울시가족센터 2센터", description: "서울시 가족 지원", phone: "0507-1360-8167", url: "https://www.familyseoul.or.kr" },
      { name: "강남구가족센터", description: "강남 가족 지원", phone: "02-3412-2222", url: "https://www.gangnam.go.kr/office/gngfamily/main.do" },
      { name: "강동구가족센터", description: "강동 가족 지원", phone: "02-471-0812", url: "https://gangdong.familynet.or.kr" },
      { name: "강북구가족센터", description: "강북 가족 지원", phone: "02-987-2567", url: "https://gangbuk.familynet.or.kr" },
      { name: "강서구가족센터", description: "강서 가족 지원", phone: "02-2606-2017", url: "https://gsfc.familynet.or.kr" },
      { name: "관악구가족센터", description: "관악 가족 지원", phone: "02-883-9383", url: "https://gwanak.familynet.or.kr" },
      { name: "광진구가족센터", description: "광진 가족 지원", phone: "02-458-0622", url: "https://gwangjin.familynet.or.kr" },
      { name: "구로구가족센터", description: "구로 가족 지원", phone: "02-869-0317", url: "https://gurofc.familynet.or.kr" },
      { name: "금천구가족센터", description: "금천 가족 지원", phone: "02-803-7743", url: "https://geumchfc.familynet.or.kr" },
      { name: "노원구가족센터", description: "노원 가족 지원", phone: "02-979-3501", url: "https://nowon.familynet.or.kr" },
      { name: "도봉구가족센터", description: "도봉 가족 지원", phone: "070-8858-6209", url: "https://dobong.familynet.or.kr" },
      { name: "동대문구가족센터", description: "동대문 가족 지원", phone: "02-957-0760", url: "https://ddmhfc.familynet.or.kr" },
      { name: "동작구가족센터", description: "동작 가족 지원", phone: "02-599-3301", url: "https://dchfc.familynet.or.kr" },
      { name: "마포구가족센터", description: "마포 가족 지원", phone: "02-3142-5482", url: "https://mapo.familynet.or.kr" },
      { name: "서대문구가족센터", description: "서대문 가족 지원", phone: "02-322-7595", url: "https://sdmfc.familynet.or.kr" },
      { name: "서초구가족센터", description: "서초 가족 지원", phone: "02-576-2851", url: "https://seocho.familynet.or.kr" },
      { name: "성동구가족센터", description: "성동 가족 지원", phone: "02-3395-9447", url: "https://sdfc.familynet.or.kr" },
      { name: "성북구가족센터", description: "성북 가족 지원", phone: "02-3290-1660", url: "https://sbfc.familynet.or.kr" },
      { name: "송파구가족센터", description: "송파 가족 지원", phone: "02-443-3844", url: "https://songpa.familynet.or.kr" },
      { name: "양천구가족센터", description: "양천 가족 지원", phone: "02-2065-3400", url: "https://ychc.familynet.or.kr" },
      { name: "영등포구가족센터", description: "영등포 가족 지원", phone: "070-4372-3534", url: "https://ydpfc.familynet.or.kr" },
      { name: "용산구가족센터", description: "용산 가족 지원", phone: "02-797-9184", url: "https://yongsan.familynet.or.kr" },
      { name: "은평구가족센터", description: "은평 가족 지원", phone: "02-376-3761", url: "https://eunpyeong.familynet.or.kr" },
      { name: "종로구가족센터", description: "종로 가족 지원", phone: "02-764-3524", url: "https://jongno.familynet.or.kr" },
      { name: "중구가족센터", description: "중구 가족 지원", phone: "02-2279-3891", url: "https://sujung.familynet.or.kr" },
      { name: "중랑구가족센터", description: "중랑 가족 지원", phone: "02-435-4142", url: "https://jungnang.familynet.or.kr" },
      { name: "서울이주여성상담센터", description: "이주여성 상담", phone: "02-733-0120", url: "https://global.seoul.go.kr" },
      { name: "한국이주여성인권센터", description: "이주여성 인권", phone: "02-393-0819", url: "https://www.wmigrant.org" },
      { name: "서울시여성능력개발원", description: "여성 직업 능력 개발", phone: "02-813-1906", url: "https://swrd.seoulwomanup.or.kr" },
      { name: "동부여성발전센터", description: "동부 여성 지원", phone: "02-460-2300", url: "https://dongbu.seoulwomanup.or.kr" },
      { name: "서부여성발전센터", description: "서부 여성 지원", phone: "070-5148-7201", url: "https://seobu.seoulwomanup.or.kr" },
      { name: "남부여성발전센터", description: "남부 여성 지원", phone: "02-2621-0010", url: "https://nambu.seoulwomanup.or.kr" },
      { name: "북부여성발전센터", description: "북부 여성 지원", phone: "02-3399-7699", url: "https://bukbu.seoulwomanup.or.kr" },
      { name: "중부여성발전센터", description: "중부 여성 지원", phone: "02-719-6307", url: "https://jungbu.seoulwomanup.or.kr" },
    ],
  },
];
